language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: h4D2wvnmBgyVLdVDBF22TkNS1RvdgHLlxHLiSi250im2SC146OCuH7ncessk3Dfgp//yy7J7IxCuhxAvlYWTh2OruMse951J47EmQQGFpxdkNKNe4AKvKjhc9fJxTLPMJG/Wu+397FuViVrZu8NWwDnsar2O+EpU2QV5hT9GhIm/1YpOjbx5OpcrUkbrzgNr/kR0QWLkCOY8EXyecEEr8TuJSeMrPBGkV5Yx3zJ4gZBsUAnSqlfsnzbkWtQ5CphxIjNSt7tAduUSI7sQfeFoHiVu7r8Zuvq12zK/ZVZkz6T7rjYJGsiXXtI6WoXpxCmQuC/Alws/Ze15A2j1yD0IKLDCACdU8aIGnqnrgLOefckxzgJeKOMicdRzAuX7g1AGSzY0V5wzSgOY8z7NwYbHJvK2e6MFlziXKK/SGKtYIcE0No/6woenpBI1xiDcW8mf463sJTv1DRIrtIe203llm8+J87Ua2txCgEEWxdxHWuEUjz8Yv+t6UI8MQH7Vrx/b7tZdC3MJm0XB7BOtTaZiJhlOIjnNtJHZU0f35RLDWF8wWe41Ds0lu9YtCjGvZNbdeLBDFOQgXWkn84SNOthNSV4ADkD2/1t6OPGFCwluBqE4r91NfeVvVUudMYC9IQndfXfk76IMClvwlFkUDmoJajysh26datRKhVQVfXeUqRk=
  app: murmuring-woodland-95064
  on:
    repo: csierra15/blog-app-mongoose-challenge-solution
